[env:nodemcuv2]
platform = espressif8266
board = nodemcuv2
framework = arduino

monitor_speed = 115200
monitor_filters =
    time

lib_deps =
    LSatan/SmartRC-CC1101-Driver-Lib
    knolleary/PubSubClient